# Use an official Ubuntu image as the base
FROM ubuntu

# Set environment variables to avoid user prompts during installation
ENV DEBIAN_FRONTEND=noninteractive
ARG CN

# Update and install Apache and OpenSSL
RUN apt-get update && apt-get install -y apache2 openssl && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /etc/ssl/copy

WORKDIR /etc/ssl/copy

RUN echo "[req]\n\
 distinguished_name = req_distinguished_name\n\
 prompt = no\n\
 \n\
 [req_distinguished_name]\n" > /etc/ssl/copy/openssl.cnf


RUN openssl ecparam -out faveoroot.key -name prime256v1 -genkey
RUN openssl req -new -sha256 -key faveoroot.key -out faveoroot.csr -subj "/C=/ST=/L=/O=/OU=/CN=" 
RUN openssl x509 -req -sha256 -days 3650 -in faveoroot.csr -signkey faveoroot.key -out faveorootCA.crt 
RUN openssl ecparam -out private.key -name prime256v1 -genkey 
RUN openssl req -new -sha256 -key private.key -out faveolocal.csr -config openssl.cnf -subj "/C=/ST=/L=/O=/OU=/CN=${CN}"
RUN openssl x509 -req -in faveolocal.csr -CA  faveorootCA.crt -CAkey faveoroot.key -CAcreateserial -out faveolocal.crt -days 3650 -sha256
    

# Expose ports 80 and 443 for HTTP and HTTPS traffic
EXPOSE 80 443

# Start Apache in the foreground
CMD ["apachectl", "-D", "FOREGROUND"]
